### ISSUE TITLE
Не использовать ругательства в качестве комментариев к коду или коммитам

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#1]
Так может получиться, что одному из участников вашей команды для собеседования потребуется показать пример кода. И его выбор падёт на этот проект. Мат же вполне может оттолкнуть потенциального работодателя.

**Comment by FRAGnatt** [comment]
На ветке мастер исправили этот недочет (в двух местах если не ошибаюсь). 
Раньше мы надеялись, что у работодателя есть чувство юмора, теперь же мы надеемся на себя )))))
