### ISSUE TITLE
    @NotNull(message = "Имя пользователя должно быть задано")

### ISSUE THREAD

**Issue by vitalii-kaplan** [SmallButTeam/LandOfDKL_project#12]
```
@NotNull(message = "Имя пользователя должно быть задано")
private String username;
@NotNull(message = "Пароль не должен быть пустым")
@Size(min = 3, message = "Минимальная длина пароля 3 символа")
private String password;

@NotNull(message="Email не должен быть пустым")
@Pattern(regexp = "^[a-zA-Z]+[a-zA-Z0-9_-]*@[a-zA-Z]+\\.[a-z]{2,}$",
        message = "Введите настоящий email")
private String email;
```

Я так понял, это сообщения пользователю.
Если да, то 
1. как вы будете их локализовывать?
2. Действительно ли 
@Entity
@Table(name="user")
public class User {

должен содержать сообщения пользователю?

**Comment by FRAGnatt** [comment]
Если мы хотим добавить не корректное значение пароля, почты и прочего, то в валидатор вернутся список сообщений
Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
  HashMap<String,String> validateResult = UserLogic.validate(user, validator);

Соответственно, мы можем создать карту [англ сообщение => русское сообщение]. Если будет необходимость в более грамотной локализации, мы вынесем в отдельный класс сообщения и константы

@Entity
@Table(name="user")
public class User {

Это указание того, что User является сущностью базы данных, а сообщения возвращает именно валидатор.

**Comment by vitalii-kaplan** [comment]
> > Если будет необходимость в более грамотной локализации, мы вынесем в отдельный класс сообщения и константы

Выносите. Перенос констант в ресурсы задание РК2

**Comment by FRAGnatt** [comment]
Сделал первую реализацию языковых пакетов. Ветка BadPracticeLangFile. Там один коммит, он переводит все сообщения в контроллере auth и создает объект для работы с языковыми настройками. Также абстрактно предполагается, что в сессии пользователя в атрибуте, уже записан его язык. После того как стопроцентно убедился, что вариант гиблый, решил его залить на отдельную ветку (не доделав) и спросить совета.

Вообщем я вижу 2 пути перевода сообщений
1) Мы в момент формирования текста, каждый кусок сообщения переводим
2) У нас в программе все сообщения на английском языке, а перед выдачей его пользователю, у нас запускается метод, который проходит по всему hashmap , и определенные куски переводит. Это может быть {"error":"text"} (смотрит на соответствие этому сообщению, ключ в словаре), или {response :{text:"Его переводит"}} или еще кого-то.

В данной реализации реализован первый вариант и он мне показался не удобным. Темболее, он не позволяет  правильно перевести следующий кусок кода (позволяет конечно, передать в message константу, а при проходом валидатором подменять сообщения, но это все слишком костыльно)

``` java
@NotNull(message="Email не должен быть пустым")
```

Просьба посмотреть на текущую реализацию и помочь написать минимально работающий прототип правильной реализации. Т.к второй способ, тоже достаточно не удобно поддерживать именно таким, как я его вижу в реализованном состоянии (а не  в теории)

P.S еще родилась идея, сделать все сообщения константами, которые являются дубликатами ключей в MessageList.properties
