### ISSUE TITLE
createWebSocket

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#14]
``` java
public Object createWebSocket(ServletUpgradeRequest request, ServletUpgradeResponse response) {
        int sessionID = 0;
        try {
            sessionID = (int) request.getSession().getAttribute("id");
        } catch (Exception e)
        {
            sessionID = 0;
        }
        if (sessionID == 0) {
            LogFactory.getInstance().getSessionLogger().debug("Util.WebChatSocketCreator/createWebSocket Not Auth");
            return null;
        } else {
            return new WebChatSocket(users, sessionID);
        }
    }
```

Не очень понятно, почему код организован таким образом. Вместо того, чтобы проверить "id" на null, вы создаётся исключение. При этом управление через значение sessionID тоже вызывает вопросы. В общем, рекомендую сократить код раза в 3.

**Comment by Jimilian** [comment]
Почему тип возвращаемого значения Object?

**Comment by FRAGnatt** [comment]
Про тип возвращаемого объекта мы с вами полностью согласны. Не безопасно да и не правильно возвращать Object.

Про оптимизацию мы с вами согласны, давайте я просто так объясню почему он так организован. Хоть это и не важно и вы правы. Делом в том, что если бы это был request.getParameter("id"), то помимо того, что этот атрибут может быть null, он также мог бы быть и строкой (а должен числом), в этом случае эксепшена не избежать, если не сделать еще массу проверок на непредвиденные ошибки. 

Вообщем вижу два способа оптимизаций 
1)

``` java
try {
            sessionID = (int) request.getSession().getAttribute("id");
            return new WebChatSocket(users, sessionID);
        } catch (Exception e)
        {
LogFactory.getInstance().getSessionLogger().debug("Util.WebChatSocketCreator/createWebSocket Not Auth");
            return null;
        }                  
```

2)

``` java
int sessionID = (request.getSession().getAttribute("id") != null)?(int)request.getSession().getAttribute("id"):0;
        if (sessionID == 0) {
            LogFactory.getInstance().getSessionLogger().debug("Util.WebChatSocketCreator/createWebSocket Not Auth");
            return null;
        } else {
            return new WebChatSocket(users, sessionID);
        }
```

**Comment by Jimilian** [comment]
Здесь тоже самое:

``` java
        try {
            userID = (int) request.getSession().getAttribute("id");
        } catch (NullPointerException e) {
            userID = 0;
        }
```

Лучше тот вариант, который читается легче. На мой вкус, это вариант номер 1. И если вы ждете два возможных исключения NPE и IllegalArgumentException - укажите их явно.
То, что вы оставляете `Exception e` - это плохой подход. IDEA это называет, кажется, "Too broad exception clause".

**Comment by FRAGnatt** [comment]
Хотел реализовать первый после вашего сообщения, но передумал т.к первый вариант не очень удачно подходит к 

``` java
try {
            userID = (int) request.getSession().getAttribute("id");
        } catch (NullPointerException e) {
            userID = 0;
        }
```

Чтобы соблюдать стилистику.

Исправил.
