### ISSUE TITLE
public class Player {     public Card cardList[];

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#15]
Плохо делать поля класса public. Это уничтожает абстракцию и усложняет тестирование.
Нужно использовать private и геттер.

**Comment by Jimilian** [comment]
И это относится не только к классу Player.

**Comment by FRAGnatt** [comment]
Весь пакет logic это нереализованная никапельки логика, над которой работа не велась и был создан он впервые дни существование проекта.
