### ISSUE TITLE
MAX_HEALTH и CARDS_AMOUNT

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#16]
``` java
    final int MAX_HEALTH = 50;
    final int CARDS_AMOUNT = 15;
```

Во-первых, они должны быть static, потому что нет смысла выделять память под одним и те же константы несколько раз.
Во-вторых, эти значения - отличные кандидаты для выноса в ресурсы.

**Comment by FRAGnatt** [comment]
Весь пакет logic это нереализованная никапельки логика, над которой работа не велась и был создан он впервые дни существование проекта.
