### ISSUE TITLE
FightFinder

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#17]
Список игр должен быть private final.

**Comment by FRAGnatt** [comment]
Весь пакет logic это нереализованная никапельки логика, над которой работа не велась и был создан он впервые дни существования проекта.

**Comment by Jimilian** [comment]
Такие штуки, чтобы не отнимать ни моё, ни ваше время лучше держать в какой-нибудь отдельной ветке. Но это так, на будущее.
