### ISSUE TITLE
CardType

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#18]
Для конечных множеств есть подходящий тип данных - Enum.

```
    //
    //type: 0 - dragon, 1 - knight, 2 - lady
    //
```

Если же от типа карты зависит поведение и у неё есть характеристики, то нужно выделить интерфейс или абстрактный класс, а различия отобразить в наследниках.

**Comment by FRAGnatt** [comment]
Весь пакет logic это нереализованная никапельки логика, над которой работа не велась и был создан он впервые дни существование проекта.
