### ISSUE TITLE
Имя класса не должно отражать внутреннюю реализацию*

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#20]
*Если речь не про коллекцию

Речь, как минимум, про AccountMap и AccountMapController.
То, что в основании аккаунт сервера лежит карта - не должно никаким образом влиять на контроллер. Нужно выделить интерфейс для аккаунт-сервера. И обращаться везде к классу через интерфейс.

Для "небоевой" реализации обычно используют приставку Fake. Может назвать реализацию аккаунт-сервера на основе карт назвать FakeAccountServer.
Но интерфейс или контроллер про "фейковость" ничего знать не должен.

**Comment by abondar** [comment]
Возможно, вы не до конца поняли в чем смысл этого класса - раньше он назывался AccountCache, что по моему мнению лучше отражало идею этого класса - он хранит в памяти всех залогированных пользователей, чтобы иметь возможность быстро получить информацию о пользователе уже после аутенфикации. Переименовали по совету из код ревью. Он не является заменой аккаунт сервера - он лишь её дополняет для более быстрой работы. Так же мэпом он называется не потому что он работает на мэпе, а потому что он по факту выполняет функциональность мэпа с разными доработками. АккаунтМэпКонтроллер - класс  не относящийся  к работе АккаунтМэп - он существует только для работы с jConsole и в коде нигде не используется.
