### ISSUE TITLE
{ this.sessionFactory = sessionFactory; }

### ISSUE THREAD

**Issue by vitalii-kaplan** [SmallButTeam/LandOfDKL_project#25]
Сейчас у вас каждый класс DAO создает транзакцию.
Что делать если нужна одна транзакция на изменение двух или более таблиц?

**Comment by FRAGnatt** [comment]
Вы хотите чтобы мы вынесли sessionFactory в DBService, а открытие\закрытие транзакции сделать через методы в DBService?

**Comment by vitalii-kaplan** [comment]
Да

**Comment by vitalii-kaplan** [comment]
транзакция для того и нужна чтобы атомарно менять несколько таблиц
