### ISSUE TITLE
Никто никогда не называет папку с тестами - UnitTest 

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#28]
Традиционно, она называется test.
Либо будьте последовательны, назовите папку с кодом - SourceCode.

Только тогда, пожалуйста, удалите из профиля проекта любые упоминания меня, Виталия, Егора и Технопарка.

**Comment by abondar** [comment]
Если я ничего не перепутал - то название UnitTest дала IDEA, когда я создал первый тест с её помощью - ну ладно - переименовал по вашему совету
