### ISSUE TITLE
testUrlParse - неплохо было бы еще проверить общую длину

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#29]
И непонятно, почему первый индекс равен "1", а не "0". Вспомнил Паскаль.

**Comment by FRAGnatt** [comment]
Потому что split("/") от "/url/" , в нулевой аргумент запишет пустоту, т.к url начинается с "/". По хорошему, конечно стоит переиндексировать массив. Но legacy код, что тут с нас взять =))) Щас исправим

**Comment by FRAGnatt** [comment]
Решено
