### ISSUE TITLE
public class Router extends HttpServlet

### ISSUE THREAD

**Issue by vitalii-kaplan** [SmallButTeam/LandOfDKL_project#3]
1. Убрать не используемые поля
   private String login = "";
   
   FightFinder fightFinder = new FightFinder();
2. убрать закоментированный код
3. не использовать return для выхода из void
4. 
   String[] urlBuf = url.split("/");
           String[] urlParts;
           if (urlBuf.length < 4){
               urlParts = new String[4];
               System.arraycopy(urlBuf,0,urlParts,0,urlBuf.length);
               urlParts[3] = "main";
           } else {
               urlParts = urlBuf;
           }

вынести в отдельный метод чтобы можно было тестировать
5.
Object obj = cls.newInstance();
            Class[] paramTypes = new Class[] {HttpServletRequest.class,HttpServletResponse.class};
            Method method = cls.getMethod(urlParts[3].toLowerCase(), paramTypes);
            Object[] args = new Object[] {request, response};
            method.invoke(obj, args);
вынести в отдельный метод чтобы можно было тестировать
1. 
   e.printStackTrace();
   System.err.println(e.getMessage() + " In Router");
   заменить на Logger

**Comment by FRAGnatt** [comment]
Весь проект перенесли на logger.

4 и 5 пункт выполнили, но как по мне читаемость кода снизилась.
