### ISSUE TITLE
GameFactoryTest - WAT?!?!

### ISSUE THREAD

**Issue by Jimilian** [SmallButTeam/LandOfDKL_project#30]
Почему несколько @Before и @After?
Вы понимаете, как они работают?

Что это?

```
gameFactory = null;
```

**Comment by abondar** [comment]
В тестах создаются сессии игр и идет поиск их в мапе игр, и соотвественно я не хотел, чтобы он искал по тем играм, которые я создавал в прошлых тестах, меня интересуют игры которые я создал в данном тесте. Но само решение неправильное, сейчас исправим.

**Comment by FRAGnatt** [comment]
Решено
