### ISSUE TITLE
 } catch (Exception e){

### ISSUE THREAD

**Issue by vitalii-kaplan** [SmallButTeam/LandOfDKL_project#7]
try {
            id = (int)request.getSession().getAttribute("id");
        } catch (Exception e){
            id = 0;
        }
если вы ждете IllegalStateException то его и пишите в catch 
и нужно добавить об этом событии запись в лог

**Comment by FRAGnatt** [comment]
Нет, мы ожидаем NullPointerException. События в лог добавлять не нужно, потому что это нормальное состояние. Если все еще залогинен(аутентифицирован), то пусть перенаправляется в игру и не проходит повторно авторизацию.

Вообще мы ждем любую ошибку, поэтому я не понимаю, зачем в таких случаях уточнять что именно мы ждем. Нету сессии ?? Пускай логинится, нету аттрибута ? Пускай логинится. Но в данном, конкретном случае мы подразумеваем именно то, что он ранее не был авторизован, или наоборот был.

Исправлено кроме логирования

**Comment by FRAGnatt** [comment]
В итоге все-равно переделали в связи с замечаниями Александра

Переделали на

``` java
int id = (request.getSession().getAttribute("id") != null)?(int)request.getSession().getAttribute("id"):0;
```

**Comment by vitalii-kaplan** [comment]
> > мы ожидаем NullPointerException

не надо ожидать NullPointerException
не надо доводить приложение до NullPointerException
какждое исключение это просадка в производительности

> > В итоге все-равно переделали

ок, а почему надо было переделать поняли? или у вас свое твердое мнение?

**Comment by FRAGnatt** [comment]
Я не очень понял почему не нужно доводить приложение до NullPointException,  если это ожидается. Тем самым вызвав любую функцию, я избегу ее повторное использование. Предположим, что getAttribute выполняет еще 100 своих действий, и два раза ее вызывать (для проверки на null и для присваивания) не желательно. 

Если я правильно понял, то доводить приложение до Exception'ов вообще не нужно, потому что создается объект исключения + записывается стек трейс и происходит еще масса действий, которая влияет на производительность. Если это так, то да, действительно. В подобных программных действиях, мы будем заключать if(resultFunction() != null). Но опять же только в тех случаях, если resultFunction() является легким методом. Или даже вообще не допускать возврата null, а возвращать скажем -1 или какой-нибудь подобный флаг

Подытожу: Я правильно понимаю, что стоит как можно чаще делать доп проверки, если они позволяют избежать Exception. И стараться вызывать Exception, когда действительно случилось что-то плохое

**Comment by vitalii-kaplan** [comment]
Подытожу: да
